// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        // return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg5q5XiHa19uIViBpbl5q-vyQilQofSQc',
    appId: '1:837515652705:android:408ffe2f3ef03514f90420',
    messagingSenderId: '837515652705',
    projectId: 'btgki-5878b',
    databaseURL: 'https://btgki-5878b-default-rtdb.firebaseio.com',
    storageBucket: 'btgki-5878b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZx4Mz01VOzw5gtEMkYoIiXpPNhbwCwRA',
    appId: '1:837515652705:ios:57c33e11e15a2fbaf90420',
    messagingSenderId: '837515652705',
    projectId: 'btgki-5878b',
    databaseURL: 'https://btgki-5878b-default-rtdb.firebaseio.com',
    storageBucket: 'btgki-5878b.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

}